---
title: "test-grades"
author: "Kenza REDWANE"
format: 
  html:
    code-fold: true
---

### Introduction

## 1.1 Study organisation

## 1.2 Data set

```{r}
#| message: false
#| cache: false
here::i_am("grades(graded).csv")
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
```

Question 1: Load data
```{r}
library(readr)
grades <- read_csv("/Users/macbookpro/Desktop/Master/Semester One/Data Management and Programming/test-grades/grades(graded).csv")

```
## Simple analyses:

Question 2:
```{r}
num_grades <- nrow(grades)
paste("The data set contains", num_grades, "grades")
```

Question 3:
```{r}
num_students <- grades |> distinct(id) |> nrow()
paste("The data set contains", num_students, "students")
```

Question 4:
```{r}
students <- grades |> distinct(id, group)
students |> slice_head(n = 5)
```

Question 5: 
```{r}
students_per_group <- students |> count(group)
ggplot(students_per_group, aes(x = factor(group), y = n)) +
  geom_col(fill='steel blue') +
  labs(title = "Number of students per group", x = "Group", y = "Number of students")
```

Question 6:
```{r}
arch_sculpture_avg <- grades |> 
  filter(course == "Architecture and Sculpture") |> 
  group_by(group) |> 
  summarise(avg_grade = mean(grade, na.rm = TRUE))

ggplot(arch_sculpture_avg, aes(x = factor(group), y = avg_grade)) +
  geom_col(fill="steel blue") +
  labs(title = "Average of grades in Architecture and Sculpture per Group", x = "Group", y = "Average of grades")
```

Question 7: Comparison
```{r}
ggplot(grades, aes(x = grade, fill = factor(semester))) +
  geom_density(alpha = 0.5) +
  labs(title = "Distribution of grades per semester ", 
       x = "Grades", 
       y = "Dennsity", 
       fill = "Semester")
```

### Attendance analysis

Question 8:
```{r}
grades_per_student <- grades |> 
  group_by(id, group) |> 
  summarise(num_grades = n())

summary_stats <- grades_per_student |> 
  summarise(min_grades = min(num_grades),
  max_grades = max(num_grades),
  avg_grades = mean(num_grades),
  med_grades = median(num_grades))
summary_stats
```

Question 9
```{r}
martial_grades <- grades |> 
  filter(course == "Martial Arts and Self-Defense") |> 
  group_by(id, group) |> 
  summarise(num_martial_grades = n())
martial_grades |> slice_head(n = 5)
```
Question 10:
```{r}
distribution_martial_grades <- martial_grades |> 
  count(num_martial_grades)
ggplot(distribution_martial_grades, aes(x = num_martial_grades, y = n)) +
  geom_col(fill ='darkred') +
  labs(title = "Distribution of grades in Martial Arts and Self-Defense", x = "Number of grades ", y = "Number of students")

```

Question 11:
```{r}
ggplot(martial_grades, aes(x = factor(group), y = num_martial_grades)) +
  geom_boxplot() +
  labs(title = "Number of grades in Martial Arts and Self-Defense per group", x = "Group", y = "Number of de grades")
```

